export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_ERROR  = 'FETCH_USERS_ERROR';
export const USER_SIGNUP  = 'USER_SIGNUP';
export const USER_LOGIN  = 'USER_LOGIN';
export const USER_SIGNUP_ERROR  = 'USER_SIGNUP_ERROR';
export const USER_LOGIN_ERROR  = 'USER_LOGIN_ERROR';
export const USER_LOGIN_SIGNUP  = 'USER_LOGIN_SIGNUP';
export const USER_LOGIN_MODAL  ='USER_LOGIN_MODAL'
export const USER_SIGNUP_MODAL ='USER_SIGNUP_MODAL'
export const  CLOSE_USER_MODAL ='CLOSE_USER_MODAL';
export const  USER_INPUT = 'USER_INPUT';

export const VERIFY_USER ='VERIFY_USER';
export const VERIFY_USER_ERROR ='VERIFY_USER_ERROR';